### ISSUE TITLE
Deep versus Flat run mode for LVS test

### ISSUE THREAD

**Issue by FaragElsayed2** [KLayout/klayout#1364] opened 2023-05-11 14:58 UTC
- For latest klayout version `0.28.6`,  we have an issue related to LVS extraction in deep mode.

But same layout could be extracted without any issues when using flat run mode.

- You could find our testing environment [HERE](https://github.com/mabrains/gdsfactory/tree/main/gdsfactory/generic_tech/klayout/lvs)

- For Deep mode:

```
 python3 run_lvs.py --layout=testing/testcases/unit/heater_devices/layout/straight_heater_metal.gds --netlist=testing/testcases/unit/heater_devices/netlist/straight_heater_metal.spice --run_mode=deep --run_dir=lvs_straight_heater_metal_deep
 ```

Results will be at `lvs_straight_heater_metal_deep` directory in same run folder.

Here is the output from netlist browser
![image](https://github.com/KLayout/klayout/assets/91015308/7f83d55e-29a1-48ec-8fdc-3ee0d23f8e61)

- For Flat mode [Or when we have flatten the layout top cell]

```
 python3 run_lvs.py --layout=testing/testcases/unit/heater_devices/layout/straight_heater_metal.gds --netlist=testing/testcases/unit/heater_devices/netlist/straight_heater_metal.spice --run_mode=flat --run_dir=lvs_straight_heater_metal_flat
```
Results will be at `lvs_straight_heater_metal_flat` directory in same run folder.

Here is the output from netlist browser
![image](https://github.com/KLayout/klayout/assets/91015308/a58d1268-c78e-44a1-a2b7-eb6670e9424b)

**Comment by FaragElsayed2** [comment] 2023-05-11 15:00
Cc @atorkmabrains

**Comment by klayoutmatthias** [comment] 2023-05-11 20:34
Thanks for this report!

I had some trouble reproducing it.

First, I did not find a GDS file. I found "straight_heater_metal.py" and it was not creating the GDS file. I had to add a "write_gds" statement and rename the cell manually to "straight_heater_metal".

In addition, the LVS deck works with 0.28.7 only with the following patch:

```
diff --git a/gdsfactory/generic_tech/klayout/lvs/rule_decks/custom_classes.lvs b/gdsfactory/generic_tech/klayout/lvs/rule_decks/custom_classes.lvs
index e6632c3cc..e37cfb504 100644
--- a/gdsfactory/generic_tech/klayout/lvs/rule_decks/custom_classes.lvs
+++ b/gdsfactory/generic_tech/klayout/lvs/rule_decks/custom_classes.lvs
@@ -44,7 +44,7 @@ class SubcircuitModelsReader < RBA::NetlistSpiceReaderDelegate
       # we need to translate the parameter values from SI to um values:
       device.set_parameter('A', ((params['W'] || 0.0) * (params['L'] || 0.0)) * 1e12)
       device.set_parameter('P', ((params['W'] || 0.0) + (params['L'] || 0.0)) * 2e6)
-      device.set_parameter('C', (params['C'] || 0.0))
+      device.set_parameter('C', (value || 0.0))
 
     when 'R'
       case nets.size
@@ -91,7 +91,7 @@ class SubcircuitModelsReader < RBA::NetlistSpiceReaderDelegate
       # we need to translate the parameter values from SI to um values:
       device.set_parameter('W', ((params['W'] || 0.0) * (params['PAR'] || 1.0)) * 1e6)
       device.set_parameter('L', ((params['L'] || 0.0) * (params['S'] || 1.0)) * 1e6)
-      device.set_parameter('R', (params['R'] * (params['S'] || 1.0) / (params['PAR'] || 1.0)))
+      device.set_parameter('R', (value * (params['S'] || 1.0) / (params['PAR'] || 1.0)))
 
     else
       return super
```

This is because there is no parameter "R" in the "R" elements of the netlist, while the value is always there (you could also use `param['R'] || 0.0`). I reworked the Spice reader for parametric circuits and apparently changed that behavior. I will restore the original behavior by always providing a "R" (or "C") parameter, but basically "value" is the right thing to use.

Now to the problem: deep mode fails because the top level cell does not have any connection to the sub cells. The devices are entirely contained in the subcells. And as there are not connections between these subcells and top cell no nets are formed in the top cell leading from top cell to sub cells.

Technically this makes the device cells individual cells and not subcircuits of the top cell. I don't know if that can be fixed in general (like: does Spice allow subcircuits without pins?). However, IMHO this quite a hypothetical case, but I am willing to change my mind if there is reason for representing isolated subcircuits in the netlist.

Anyway, having said this the fix is simple: I copied all shapes on layer 45 to the top cell rendering metal connections between top cell and the device cells. This makes LVS match :)

Modified GDS file is attached.

[straight_heater_metal.gds.zip](https://github.com/KLayout/klayout/files/11456132/straight_heater_metal.gds.zip)

**Comment by atorkmabrains** [comment] 2023-05-12 05:32
@klayoutmatthias I think the point is that the device recognition layers are hierarchical. That cause the devices not to be recognized. I was thinking that Klayout would recognize the formation of the device regardless of the connectivity. I was thinking that Klayout might flatten some cells in the hierarchy to get all shapes at the same hierarchy level for extraction.

You have a valid point that we need to have connection for devices. 

@FaragElsayed2 Could you add a metal connection for the devices? Use GDS factory router on M3 for that. And keep the device with different hierarchy.

**Comment by klayoutmatthias** [comment] 2023-05-12 21:08
@atorkmabrains Well, basically the devices are recognized. But they sit in subcells. Usually subcells are identified with subcircuits - in this case only temporarily until "align" will flatten them as there is no correspondence in the schematic.

However, the problem in this case is that the device subcells are not even subcircuits as they are not connected to anything inside the top cell. So they are kind of "alien" and not put into the schematic's top circuit at all. They simply vanish. This makes certain sense for example for dummy fill tiles or labeling cells. 

Even if I would put them into the top circuit, it's not clear where the pins are - so basically which parts are propagated to top circuit pins. GDS does not feature pin shapes, so you can't mark a net for pin propagation. The only thing that makes a pin on a net is some shape in the top cell that touches some shape from the device cell. So once this is there, everything should be fine.

Matthias

**Comment by klayoutmatthias** [comment] 2023-05-12 21:11
Is it OK to close this ticket?

**Comment by atorkmabrains** [comment] 2023-05-14 06:51
@klayoutmatthias Give us a few days, we will add a small test and get back to you.

**Comment by FaragElsayed2** [comment] 2023-05-14 07:15
@atorkmabrains I have connected them, klayout could extract them as a one resistor [Combined as expected] --> Deep mode

So I think it's okay to close this ticket.
![image](https://github.com/KLayout/klayout/assets/91015308/c609a774-825a-4c22-aa18-1a6845d322b7)
![image](https://github.com/KLayout/klayout/assets/91015308/72dd7b63-bfa8-4206-9589-a0606e4db231)

**Comment by FaragElsayed2** [comment] 2023-05-14 07:41
@atorkmabrains After disabling devices combination, it matches
![image](https://github.com/KLayout/klayout/assets/91015308/9f379bcd-76b4-4037-adea-3241a74b3e3f)

**Comment by atorkmabrains** [comment] 2023-05-14 07:48
Thanks @FaragElsayed2

**Comment by atorkmabrains** [comment] 2023-05-14 07:48
@klayoutmatthias We could close the this ticket.

**Comment by klayoutmatthias** [comment] 2023-05-14 15:56
Thanks, guys!

**Closed by klayoutmatthias** 2023-05-14 15:56 UTC
