### ISSUE TITLE
Feature Request: toggle on/off editor options window

### ISSUE THREAD

**Issue by g2hollow** [KLayout/klayout#918] opened 2021-10-13 16:42 UTC
Hello,

Upon updating to 0.27.x I find that every time I click the menu button to create a new shape (polygon, box, etc), the 'editor options' window pops up. I can dock this window which helps a bit, but I would like the option to not have it present when creating new shapes. Most of the time once I've set up the editor options I don't need to change them very frequently, and this floating or docked window is taking up a lot of GUI real-estate especially on smaller laptop screens. Prior to 0.27.x this didn't seem to be the behavior I experienced, if it would be possible to add some menu option to prevent 'editor options' from popping up or needing to be docked it would be appreciated.

Best,
-Greg

**Comment by g2hollow** [comment] 2021-10-13 21:09
Thank you for your consideration, and explanation. I understand your reasoning. Also thank you for creating this software and continuing to maintain it, it is fantastic.

**Comment by g2hollow** [comment] 2021-10-13 23:29
Perhaps I closed this pre-emptively. I was just playing around with a few versions and I see why I was initially concerned with the loss of realestate. Therefore I'll reopen and explain. 

In version 0.27.4 the docked window can only be shrunk so far. In this case the docked window takes up approximately 1/3 of my window with my resolution settings. It is quite a dramatic change in view from previous versions.

![docked_0 27 4](https://user-images.githubusercontent.com/70447243/137226385-8dfc6c87-784a-4a80-9e05-47696c517262.png)

For comparison in 0.27.3 the docked window can be shrunk significantly so that this left menu bar is a similar width to previous versions. In this case the loss of realestate is negligible.

![docked_0 27 3](https://user-images.githubusercontent.com/70447243/137226407-3286f9db-abc4-4c27-8301-8d3ecf7a2136.png)

Would it be possible to be able to resize the window in 0.27.4 like it was in 0.27.3. In this case I would be completely satisfied. My apologies for flip-flopping around on this.

**Comment by lukasc-ubc** [comment] 2021-10-14 00:19
I noticed this as well.  One solution is to rip away the Editor Options window.  Unfortunately, the Escape key doesn’t close the window; you have to click with your mouse to close it.  Also the behaviour of keys like <Return> doesn’t do what I would expect (make the window go away, or apply the changes) — rather it zooms in the layout.  Maybe if the hot key “E” brought up the Editor Options window, then pushing “E” again closed it, that would help.

**Comment by Kazzz-S** [comment] 2021-10-14 22:07
Here are some quick test results on Mac.
It looks that the issue is Qt 5.15.x-specific.
Kazzz-S

![Standard-5 15 2](https://user-images.githubusercontent.com/16847255/137401929-d851c0f3-2d3b-469a-826f-0558b0a23519.png)

![MacPorts-5 12 2](https://user-images.githubusercontent.com/16847255/137401968-d237083c-ba58-43ca-8129-286df2f12968.png)

![Homebrew-5 15 2](https://user-images.githubusercontent.com/16847255/137401984-9e68061c-0d2e-434d-a89c-94839c2d7eb0.png)

![Anaconda-5 9 7](https://user-images.githubusercontent.com/16847255/137402002-b96b52d0-d8c9-4346-9e90-1105c2f36ea3.png)

**Comment by Kazzz-S** [comment] 2021-10-15 09:27
Hi, @klayoutmatthias,

I have tested with c48f930
Thank you for fixing this problem.
Kazzz-S

![patchVersion](https://user-images.githubusercontent.com/16847255/137464841-aa269fb9-2191-4f20-a466-be429bb9153e.png)

![patchST-5 12 2](https://user-images.githubusercontent.com/16847255/137464901-7c09727e-fc33-4cba-a102-e2b7b448a5ae.png)

![patchMacPorts-5 12 2](https://user-images.githubusercontent.com/16847255/137464924-9cb156b1-973b-41b7-bd33-808993f8189c.png)

![patchHomebrew-5 12 2](https://user-images.githubusercontent.com/16847255/137464943-3bdcf368-c345-438a-87b5-10534a717f27.png)

![patchAnaconda3-5 9 7](https://user-images.githubusercontent.com/16847255/137465004-611b42cf-f3d1-471c-ac89-e8e712b47496.png)

**Closed** 2021-10-15 20:11 UTC
Labels: for-0.27
