### ISSUE TITLE
facing a error while run the RTL to GDS II for GCD file (error is installing the klayout) on centos 7

### ISSUE THREAD

**Issue by Pratiknavadiya-12** [KLayout/klayout#650] opened 2020-10-06 04:47 UTC
I am getting the following error even I install the QT

Project ERROR: Unknown module(s) in QT: designer multimedia multimediawidgets xmlpatterns svg

Running build (gmake all) ..
gmake: *** No targets specified and no makefile found. Stop.

How to resolve this? please help me.

**Comment by klayoutmatthias** [comment] 2020-10-08 22:58
See https://github.com/KLayout/klayout/issues/649. 

This is not a bug. I'll close this ticket too.

**Closed by klayoutmatthias** 2020-10-08 22:58 UTC
