### ISSUE TITLE
dxf file parsing error, about spline curve

### ISSUE THREAD

**Issue by libaineu2004** [KLayout/klayout#1422] opened 2023-07-14 03:26 UTC
I found a problem with parsing errors on dxf's spline curve. Here uploaded 3 dxf files, you can use klayout and AutoCAD for comparison. You can see that there are problems with spline curve analysis, either with more lines or less lines.

klayout version
0.28.8

dxf with spline
https://github.com/libaineu2004/myepolltest/releases/download/dxf/bo.dxf
https://github.com/libaineu2004/myepolltest/releases/download/dxf/potato.dxf
https://github.com/libaineu2004/myepolltest/releases/download/dxf/R.dxf

**Comment by klayoutmatthias** [comment] 2023-07-15 11:48
I do not have AutoCAD for comparison. Could you paste some reference images and describe the expected output?

**Comment by klayoutmatthias** [comment] 2023-07-15 11:54
I used an online viewer, so now your files are on their servers. I guess you don't care ...

I see the difference here:

KLayout:
![image](https://github.com/KLayout/klayout/assets/25720841/f34c722f-5a73-4885-9d68-d8599a85da7a)

Viewer:
![image](https://github.com/KLayout/klayout/assets/25720841/d2163869-cec7-48fe-9418-4fcac18b0b0b)

So I think this is what you mean.

**Comment by klayoutmatthias** [comment] 2023-07-15 12:45
I debugged the problem and I think I fixed it. Reason was an exceptionally high point density in certain segments.

Here are my outputs now:

"R":
![image](https://github.com/KLayout/klayout/assets/25720841/1dceba33-167f-4ce5-a84f-8f0a09e89e35)

"potato":
![image](https://github.com/KLayout/klayout/assets/25720841/6fc5d2e2-9197-4bed-95f1-5dde29ded0b4)

"bo":
![image](https://github.com/KLayout/klayout/assets/25720841/92ba2a78-deb7-4b9c-9f40-5575e41e963a)

I could not find an online viewer that displays "R" and "potato", so maybe you can confirm that now that is the correct rendering.

Matthias

**Comment by klayoutmatthias** [comment] 2023-07-15 14:07
Ok, found the issue. Potato looks like this now:

![image](https://github.com/KLayout/klayout/assets/25720841/0d514203-a5dd-4b78-8dc8-0056e802eb41)

I guess that fixes it.

**Comment by libaineu2004** [comment] 2023-07-15 15:16
> online viewer

What is the web address of the online viewer you are visiting? What is the url?

**Comment by libaineu2004** [comment] 2023-07-15 15:20
klayout version
0.28.8

"R.dxf" is:
![S`UTW5$ZUV $PD_NV88(~B4](https://github.com/KLayout/klayout/assets/11898277/3c73d0e4-6dc1-4384-818e-1ad7f8241d89)

**Comment by klayoutmatthias** [comment] 2023-07-15 18:31
I tried that online viewer: https://products.groupdocs.app/viewer/total, but also others had difficulties with "R" and "potato".

Anyway, if the "R" with the circular frame is correct it looks like I have fixed the problem.

**Comment by klayoutmatthias** [comment] 2023-07-15 18:37
This one (https://3axis.co/dxf-viewer/dxf-viewer/) shows the "R" like KLayout now:

![image](https://github.com/KLayout/klayout/assets/25720841/9ed27e6b-f242-4d0e-b19a-e2a983a304c1)

But the potato looks strange:

![image](https://github.com/KLayout/klayout/assets/25720841/23e06bb0-a147-4e47-9eb7-a0134061a16e)

I guess nobody is perfect ...

**Comment by libaineu2004** [comment] 2023-07-16 01:31
> Anyway, if the "R" with the circular frame is correct it looks like I have fixed the problem.

autocad is correct. Also, qcad is correct.
https://qcad.org/en/

**Comment by klayoutmatthias** [comment] 2023-07-16 13:56
Thanks for pointing me to qcad ... I tried FreeCAD, but it did not like the splines.

**Comment by libaineu2004** [comment] 2023-07-20 12:05
Have all the problems been solved? Can you tell me what has been changed in the source code?
thank you

**Comment by klayoutmatthias** [comment] 2023-07-20 17:16
Code change is thias :https://github.com/KLayout/klayout/pull/1423/commits/35e42a81178aa3fe071a7f656a4c026eeb596679

The PR is linked tovthias ticket and will be merged soon into master.

**Comment by libaineu2004** [comment] 2023-07-21 03:50
> Code change is this :[35e42a8](https://github.com/KLayout/klayout/commit/35e42a81178aa3fe071a7f656a4c026eeb596679)
> 
> The PR is linked to this ticket and will be merged soon into master.

I tried using PR's new code and found that the program would blink.
https://github.com/KLayout/klayout/commit/35e42a81178aa3fe071a7f656a4c026eeb596679

I'm already in the function spline_interpolate. Added：
assert(pe ! = curve_points.end());
![image](https://github.com/KLayout/klayout/assets/11898277/57aa93b8-14b7-4bda-8f69-cbe76c319f64)

The assertion will take effect and an error will be reported.

I opened the following three dxf files with the same problem. My programming environment is VS2019 x64.
bo.dxf
potato.dxf
R.dxf

**Comment by klayoutmatthias** [comment] 2023-07-21 05:19
I am using exactly these files as unit test cases and they work in my case.

**Comment by libaineu2004** [comment] 2023-07-21 06:16
> 
yes, debug mode

**Comment by klayoutmatthias** [comment] 2023-07-21 16:51
Please use the wip2 branch tip. The code reference was just for your information, not for reproducing the solution. 

wip2 branch works for me on Linux and Windows.

Find the golden data for the tests here: https://github.com/KLayout/klayout/tree/wip2/testdata/dxf (issue_1422a_au.gds.gz to issue_1422c_au.gds.gz).

Matthias

**Comment by libaineu2004** [comment] 2023-07-22 01:39
> potato.dxf

Could you just tell me. For these three dxf files, which source files have the source code changed? Besides dbDXFReader.cc, are there any other files that need to be modified?

I look at the https://github.com/KLayout/klayout/commit/35e42a81178aa3fe071a7f656a4c026eeb596679, only dbDXFReader. Cc file is modified. But the potato.dxf problem was not solved.

**Comment by klayoutmatthias** [comment] 2023-07-22 15:51
I'm sorry, but https://github.com/KLayout/klayout/pull/1423/commits/35e42a81178aa3fe071a7f656a4c026eeb596679 are the only changes made. It should be enough to apply the changes of dbDXFReader.cc - the other modifications are only new tests to cover your case. The potato is reproduced without the sticks on MSVC2017, CentOS7 and Ubuntu 22 for me.

**Comment by klayoutmatthias** [comment] 2023-07-22 15:57
I've put in an assertion and I can reproduce the array out of bounds issue. I will debug it.

**Comment by klayoutmatthias** [comment] 2023-07-22 16:15
I have placed one more patch: https://github.com/KLayout/klayout/pull/1423/commits/99df15a5fff7fd6ac0f64b781d34cb2b2a4bc706 - this should fix the potato issue.

**Comment by libaineu2004** [comment] 2023-07-23 01:33
> I have placed one more patch: [99df15a](https://github.com/KLayout/klayout/commit/99df15a5fff7fd6ac0f64b781d34cb2b2a4bc706) - this should fix the potato issue.

Yes.
https://github.com/KLayout/klayout/commit/99df15a5fff7fd6ac0f64b781d34cb2b2a4bc706
The result of my test is correct.
Thank you!

**Comment by klayoutmatthias** [comment] 2023-07-23 07:16
Very good. I'll merge the PR then.

Matthias

**Closed** 2023-08-08 22:33 UTC
Labels: bug
