### ISSUE TITLE
Object cannot be created here in QWidget_Native.show

### ISSUE THREAD

**Issue by tkoyat** [KLayout/klayout#490] opened 2020-02-03 16:59 UTC
import ......
from lay import *
if __name__ == "__main__":
    app = QApplication(sys.argv)
    try:
        form = MainWindow()
        form.show()
        sys.exit(app.exec_())
    except Exception as e:
        print(e)

debug: <klayout.lay.MainWindow object at 0x000001F2DDB50B40>

**Comment by tkoyat** [comment] 2020-02-03 17:01
Hi Matthias:
how to use lay show MainWindow?

**Comment by klayoutmatthias** [comment] 2020-02-03 21:06
Closed as duplicate of #479.

**Closed by klayoutmatthias** 2020-02-03 21:06 UTC
Labels: duplicate
