### ISSUE TITLE
deep-only crash, 0.27.4 & 0.27.13: ERROR: 'interacting': Internal error: /var/lib/jenkins/workspace/multibranch-centos7_staging/src/db/db/dbShape.h:1239 m_type == PolygonRef was not true in Region::interacting

### ISSUE THREAD

**Issue by sto6** [KLayout/klayout#1203] opened 2022-12-03 21:55 UTC
A script to recreate. Works in flat; crash in deep. Data source shown within. My tests were all/only on centos-7.9.
Is there a rewrite to avoid the issue? Thank you.

```
#!/bin/bash
# in bash:
x=%{

# self-log
lg=hres-10.log
mv -f $lg $lg-bak
exec </dev/null &> >(/usr/bin/tee $lg)
exec klayout -b -r "$0"
}
# in klayout/ruby:

STDOUT.sync = true
STDERR.sync = true
puts "start"

# get it here: https://github.com/whutddk/Rift2Go_2300_GF180_MPW0/blob/a269c5678626b943e0d1121c67e60913fc28f53f/gds/user_project_wrapper.gds.gz
source( "user_project_wrapper.gds.gz", "gf180mcu_fd_sc_mcu7t5v0__buf_16")
report( "hres-10", "/tmp/hres-10.log")

deep   # vs flat

poly2 = polygons(30 , 0).merged
pplus = polygons(31 , 0).merged
hres = poly2.interacting(pplus)
hr1 = pplus.drc(width != 0.1.um)
hr3 = hr1.or(pplus.edges).extended(0, 0, 0.001, 0.001)
hr4 = hr3.interacting(hres)    # <--- crash in deep, ok in flat
puts "done"
```

Sample output (0.27.13):
```
start
ERROR: /var/lib/jenkins/workspace/multibranch-centos7_staging/src/db/db/dbShape.h,1239,m_type == PolygonRef
ERROR: In ./hres-10.drc: 'interacting': Internal error: /var/lib/jenkins/workspace/multibranch-centos7_staging/src/db/db/dbShape.h:1239 m_type == PolygonRef was not true in Region::interacting
ERROR: 'interacting': Internal error: /var/lib/jenkins/workspace/multibranch-centos7_staging/src/db/db/dbShape.h:1239 m_type == PolygonRef was not true in Region::interacting in Executable::execute
  ./hres-10.drc:28:in `execute'
  :/built-in-macros/drc_interpreters.lym:27:in `instance_eval'
  :/built-in-macros/drc_interpreters.lym:27:in `execute'
```

**Comment by klayoutmatthias** [comment] 2022-12-04 22:17
This is a duplicate of https://github.com/KLayout/klayout/issues/1190. It has been fixed in master and will be released with 0.28.

BTW: you can install master from here: https://www.klayout.org/downloads/master. CentOS 7 can be installed with:

```
yum install https://www.klayout.org/downloads/master/centos7/klayout-master-0.x86_64.rpm
```

Closing this ticket as it's a duplicate.

Matthias

**Closed by klayoutmatthias** 2022-12-04 22:17 UTC
